name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          3.1.x
          5.0.x
          6.0.x
    - name: Install dependencies
      run: dotnet restore src/AdventOfCode.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore src/AdventOfCode.sln
    - name: Test
      run: dotnet test --no-restore --verbosity normal src/AdventOfCode.sln
